# kubectl create -f app-secret.yaml  
# echo -n 'password' | base64     or  echo 'T3JhQDIwMjEucGFzc3dk' | base64 -d
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: redis
type: Opaque
data:
  password: T3JhQDIwMjEucGFzc3dk

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: redis
type: Opaque
data:
  password: STNnUXFGbHh4VQ==
